### ISSUE TITLE
unix: crash when destroying an indeterminate progressbar

### ISSUE THREAD

**Issue by emersion** [andlabs/libui#163]
```
(main:23028): Gtk-CRITICAL **: gtk_progress_bar_pulse: assertion 'GTK_IS_PROGRESS_BAR (pbar)' failed
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x19 pc=0x7f49b7a19e36]

runtime stack:
runtime.throw(0x9d54a0, 0x2a)
	/usr/lib/go/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
	/usr/lib/go/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 5 [syscall, locked to thread]:
runtime.cgocall(0x79b8d0, 0xc820039f20, 0x0)
	/usr/lib/go/src/runtime/cgocall.go:123 +0x11b fp=0xc820039ef8 sp=0xc820039ec8
github.com/andlabs/ui._Cfunc_uiMain()
	??:0 +0x36 fp=0xc820039f20 sp=0xc820039ef8
github.com/andlabs/ui.start(0xc82005e180, 0xa10580)
	/home/simon/go/src/github.com/andlabs/ui/main.go:56 +0x1f3 fp=0xc820039fa0 sp=0xc820039f20
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820039fa8 sp=0xc820039fa0
created by github.com/andlabs/ui.Main
	/home/simon/go/src/github.com/andlabs/ui/main.go:36 +0x6d

goroutine 1 [chan receive]:
github.com/andlabs/ui.Main(0xa10580, 0x0, 0x0)
	/home/simon/go/src/github.com/andlabs/ui/main.go:37 +0x9d
github.com/ProtonMail/(super-secret-project)/frontend_ui.Main()
	/home/simon/go/src/github.com/ProtonMail/(super-secret-project)/frontend_ui/main.go:9 +0x23
main.main()
	/home/simon/go/src/github.com/ProtonMail/(super-secret-project)/main.go:11 +0x2d

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1998 +0x1
exit status 2
```

**Comment by andlabs** [comment]
Yes, because I forgot to destroy the timeout source. I'll get to that shortly.

**Comment by emersion** [comment]
Would you prefer modifying `uiControlDestroy` or `pulse` to solve this? I think pulse would be better, even if the timer won't be destroyed right after the progressbar.

**Comment by andlabs** [comment]
I'll take care of it now.
