### ISSUE TITLE
Cannot find module 'yoga-layout'

### ISSUE THREAD

**Issue by davidsylvestre** [andlabs/libui#333]
Hi.

(Sorry for the glitches in English, I had to use the translator)

By performing the quick-start of the documentation, I came across the error below.

```shell
>npm run start

> teste-proton@0.0.1 start c:\backup\projetos\javascript\teste-proton
> babel-node index.js

module.js:540
    throw err;
    ^

Error: Cannot find module 'yoga-layout'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (c:\backup\projetos\javascript\teste-proton\node_modules\proton-native\bin\components\View.js:23:19)
    at Module._compile (module.js:643:30)
    at Module._extensions..js (module.js:654:10)
    at Object.require.extensions.(anonymous function) [as .js] (c:\backup\projetos\javascript\teste-proton\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! teste-proton@0.0.1 start: `babel-node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the teste-proton@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\david\scoop\persist\nodejs-lts\cache\_logs\2018-04-04T17_28_14_560Z-debug.log
```

```json
{
  "name": "teste-proton",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node_modules/.bin/babel-node index.js",
    "build": "node_modules/.bin/babel index.js -d bin/",
    "package-linux": "bash ./scripts/appimage.sh"
  },
  "dependencies": {
    "babel-cli": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "proton-native": "^1.0.17"
  }
}
```

**Comment by parro-it** [comment]
I think you should post this issue on [proton-native repo](https://github.com/kusti8/proton-native).

**Comment by davidsylvestre** [comment]
Sorry.

**Comment by davidsylvestre** [comment]
Opened Issue [#79](https://github.com/kusti8/proton-native/issues/79)
